<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_63f91bb05293e',
	'title' => 'Speaker\'s modal',
	'fields' => array(
		array(
			'key' => 'field_63f91bb01566a',
			'label' => '',
			'name' => 'speakers_modal',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'sub_fields' => array(
				array(
					'key' => 'field_63f91cbc15670',
					'label' => 'Modal\'s Settings',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'field_64513887d8d82',
					'label' => 'Style of modal',
					'name' => 'style_of_modal',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'horizontal' => 'Horizontal',
						'vertical' => 'Vertical',
					),
					'default_value' => 'horizontal',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'allow_custom' => 0,
					'search_placeholder' => '',
				),
				array(
					'key' => 'field_63f91ca81566f',
					'label' => 'Speaker name colour',
					'name' => 'speaker_name_colour',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63f91c001566b',
					'label' => 'Show Job title',
					'name' => 'show_job_title',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_63f91c401566c',
					'label' => 'Job title colour',
					'name' => 'job_title_colour',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63f91c8b1566d',
					'label' => 'Show Company name',
					'name' => 'show_company_name',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_63f91c991566e',
					'label' => 'Company name colour',
					'name' => 'company_name_colour',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000',
					'enable_opacity' => 0,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63ee3cf654b34',
					'label' => 'Link to programme',
					'name' => 'link_to_programme',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => 'Enable a link in the Speaker modal to link the session to the respective information in the programme page.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'no_link' => 'No link',
						'link_to_programme' => 'Add a link in sessions',
					),
					'default_value' => 'no_link',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'allow_custom' => 0,
					'search_placeholder' => '',
				),
				array(
					'key' => 'field_63ee3d5c54b35',
					'label' => 'Programme page link',
					'name' => 'programme_page_link',
					'aria-label' => '',
					'type' => 'page_link',
					'instructions' => 'The programme page MUST be using the programme page template',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_63ee3cf654b34',
								'operator' => '==',
								'value' => 'link_to_programme',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'post_type' => '',
					'taxonomy' => '',
					'allow_archives' => 1,
					'multiple' => 0,
					'allow_null' => 0,
				),
				array(
					'key' => 'field_63ee4631e9b49',
					'label' => 'Programme link caption',
					'name' => 'programme_link_caption',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Text to be use as the link.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_63ee3cf654b34',
								'operator' => '==',
								'value' => 'link_to_programme',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'default_value' => 'Check it in programme',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_63ecfa47d503a',
					'label' => 'Modal\'s Captions',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'field_63ecfae7d503d',
					'label' => 'Captions group',
					'name' => 'captions_group',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => 'This captions only affect the modals with information coming from Synclogic',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'layout' => 'block',
					'acfe_seamless_style' => 0,
					'acfe_group_modal' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_63ecfaf1d503e',
							'label' => 'Presentations title',
							'name' => 'presentations_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Presentation/s',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_63ecfb05d503f',
							'label' => 'Chair',
							'name' => 'chair',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Chair',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_63ecfb0dd5040',
							'label' => 'Co-chair',
							'name' => 'co_chair',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Co-chair',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_63ecfb3bd5041',
							'label' => 'Speaker',
							'name' => 'speaker',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Speaker',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'acfe_group_modal_close' => 0,
					'acfe_group_modal_button' => '',
					'acfe_group_modal_size' => 'large',
				),
			),
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/shocklogic-synclogic-speakers',
			),
		),
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/shocklogic-speakers-slider-wordpress',
			),
		),
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/shocklogic-speakers-wordpress',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'tpl/programme.php',
			),
		),
	),
	'menu_order' => -1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => 'Speaker\'s modal',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'speakers' => 'Speakers',
	),
	'modified' => 1683214373,
));

endif;